### ISSUE TITLE
bug: package opentrons-hardware is not published to pypi

### ISSUE THREAD

**Issue by strangemonad** [Opentrons/opentrons#14208]
### Overview

We're developing new in-house protocols for the Flex. We're trying to get our local project setup with correct dependencies so we can both run CI tests with the sim and deploy those programs.

package `opentrons==7.0.2` includes `opentrons/hardware_control/ot3api.py` which tries to import opentrons_hardware which does not exist / is not installed as a package.

If we install the pre-release `opentrons==7.1.0b0`, it has extras for ot2-hardware and flex-hardware (which seems to install the additional `python-can` transitive dependency but `opentrons-hardware` is not published to pypi.

### Current behavior

We've temporarily worked around this issue in with patches to our poetry project's dependencies

```toml
[tool.poetry.dependencies]
python = ">=3.7.17,<3.8"
opentrons = "7.1.0b0"
opentrons-hardware = {git="https://github.com/Opentrons/opentrons.git", tag="v7.1.0-beta.0", subdirectory="hardware", extras=["FLEX"]}
```

### Expected behavior

pacakge `opentrons-hardware` is published to pypi with matching versions to package `opentrons`

### Operating system

None

### System and robot setup or anything else?

We're using a mix of OT2 and Flex
